[2025-04-02T08:09:10.396+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-02T08:09:11.059+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag_name.create_table scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2025-04-02T08:09:11.125+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag_name.create_table scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2025-04-02T08:09:11.125+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-02T08:09:11.341+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryCreateTableOperator): create_table> on 2022-11-29 00:00:00+00:00
[2025-04-02T08:09:11.530+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6246) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-02T08:09:11.587+0000] {standard_task_runner.py:72} INFO - Started process 6285 to run task
[2025-04-02T08:09:11.593+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag_name', 'create_table', 'scheduled__2022-11-29T00:00:00+00:00', '--job-id', '1407', '--raw', '--subdir', 'DAGS_FOLDER/con.py', '--cfg-path', '/tmp/tmprb91m47x']
[2025-04-02T08:09:11.643+0000] {standard_task_runner.py:105} INFO - Job 1407: Subtask create_table
[2025-04-02T08:09:12.713+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag_name.create_table scheduled__2022-11-29T00:00:00+00:00 [running]> on host 900d630d7d5f
[2025-04-02T08:09:14.859+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag_name' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2022-11-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-11-29T00:00:00+00:00'
[2025-04-02T08:09:14.876+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-02T08:09:14.891+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-02T08:09:14.892+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2025-04-02 08:09:11.060092+00:00
[2025-04-02T08:09:14.893+0000] {logging_mixin.py:190} INFO - Dag name:my_dag_name and current dag run status:running
[2025-04-02T08:09:14.898+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-02T08:09:15.030+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-02T08:09:15.130+0000] {base.py:84} INFO - Retrieving connection 'gcp_co'
[2025-04-02T08:09:15.132+0000] {bigquery.py:1274} INFO - Creating table...
[2025-04-02T08:09:15.880+0000] {bigquery.py:1304} INFO - Table fake_news_detection.training_data already exists.
[2025-04-02T08:09:16.003+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-02T08:09:16.011+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_dag_name, task_id=create_table, run_id=scheduled__2022-11-29T00:00:00+00:00, execution_date=20221129T000000, start_date=20250402T080911, end_date=20250402T080916
[2025-04-02T08:09:16.334+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-02T08:09:16.340+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-02T08:09:16.344+0000] {logging_mixin.py:190} INFO - Dag name:my_dag_name queued_at:2025-04-02 08:08:07.305661+00:00
[2025-04-02T08:09:16.345+0000] {logging_mixin.py:190} INFO - Task hostname:900d630d7d5f operator:BigQueryCreateTableOperator
[2025-04-02T08:09:16.468+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-02T08:09:16.574+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-02T08:09:16.581+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-02T08:09:16.633+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
